### ISSUE TITLE
Add complex number scalar type support

### ISSUE THREAD

**Issue by mileschen360** [conda-forge/petsc-feedstock#17] opened 2017-09-21 20:43 UTC
Hi,
Is is possible to compile a version of petsc  --with-scalar-type=complex?

**Comment by mileschen360** [comment] 2017-09-21 21:22
I tried to build my own package base on this recipe, but failed with the following error:

          CC arch-conda-c-opt/obj/src/tao/linesearch/impls/gpcglinesearch/gpcglinesearch.o
          CC arch-conda-c-opt/obj/src/tao/leastsquares/impls/pounders/pounders.o
          CC arch-conda-c-opt/obj/src/tao/leastsquares/impls/pounders/gqt.o
     CLINKER /home/mschen/miniconda2/conda-bld/petsc_1506028791453/work/arch-conda-c-opt/lib/libpetsc.so.3.7.6
gmake[2]: warning:  Clock skew detected.  Your build may be incomplete.
gmake[2]: Leaving directory `/home/mschen/miniconda2/conda-bld/petsc_1506028791453/work'
=========================================
gmake[1]: warning:  Clock skew detected.  Your build may be incomplete.
gmake[1]: Leaving directory `/home/mschen/miniconda2/conda-bld/petsc_1506028791453/work'
**************************ERROR*************************************
  Error during compile, check arch-conda-c-opt/lib/petsc/conf/make.log
  Send it and arch-conda-c-opt/lib/petsc/conf/configure.log to petsc-maint@mcs.anl.gov
********************************************************************

**Comment by dalcinl** [comment] 2017-09-22 08:38
We could provide complex builds of petsc using conda features.

About the error you got, where are you building the recipe? These warnings come from GNU make, likely because some of your files have modification times that are ahead of the current system time. could you clean the build, `find  -type f  -exec touch {} +`, and try again?

**Comment by mileschen360** [comment] 2017-09-22 18:29
@dalcinl Thanks for your reply. The build is on the head node of a HPC cluster with CentOS 7.2. The clock skew I think is due to the non-synchronized NFS time and local machine time.

I am new to conda, which folder to run that command?

**Comment by dalcinl** [comment] 2017-09-27 12:57
Mmm. I guess you have to add it in the `build.sh` script, before configure.

**Comment by mileschen360** [comment] 2017-09-27 15:24
> find -type f -exec touch {} +
got rid of the clock skew warning, but didn't resolve the error.

**Comment by dalcinl** [comment] 2017-09-28 07:57
Hard to tell what's going on without access to the failing build. Can you see anything suspicious in `arch-conda-c-opt/lib/petsc/conf/make.log` ? Was the library `arch-conda-c-opt/lib/libpetsc.so.3.7.6` generated? Could you run `ldd arch-conda-c-opt/lib/libpetsc.so.3.7.6` so see if all library dependencies are right?

**Comment by jcmgray** [comment] 2020-02-12 19:17
Just thought I'd inquire about a complex version of petsc (slepc etc) on conda-forge here again, as it would be very useful. 

Would it just be a matter of copying this repository with `build.sh` and `--with-scalar-type=complex` to a new recipe, `petsc-complex` etc, or do you know if it could be handled simply as a separate `build` version (c.f. choice of BLAS)?

**Comment by sigvaldm** [comment] 2020-03-20 14:26
I also need this, and adding `--with-scalar-type=complex` in `build.sh` worked for me. I built it with `conda build recipe` and `conda install --use-local petsc`. Same procedure with petsc4py afterwards, to get it to work with my PETSc version. How would this best be added as an option in Conda, though? Perhaps I could contribute. I'm currently looking into variants in the Conda documentation.

**Comment by sigvaldm** [comment] 2020-03-20 14:46
Works with SLEPc and slepc4py too.

**Comment by pancetta** [comment] 2020-04-02 18:59
@sigvaldm Could you share some details on how you did it? We're having trouble getting a working version of petsc4py with complex numbers (in parallel) and your approach seems to work well!

**Comment by sigvaldm** [comment] 2020-04-03 12:00
Sure, I'll try. I haven't actually tested it in parallel, but I suppose it should work just as well as the non-complex one.

I cloned the petsc-feedstock repository (this) and added `--with-scalar-type=complex` in `python ./configure` in `recipe/build.sh`. Here's the diff:

```
diff --git a/recipe/build.sh b/recipe/build.sh
index c895011..53fab94 100755
--- a/recipe/build.sh
+++ b/recipe/build.sh
@@ -72,6 +72,7 @@ python ./configure \
   --with-superlu_dist=$WITH_SUPERLU_DIST \
   --with-suitesparse=1 \
   --with-x=0 \
+  --with-scalar-type=complex \
   --prefix=$PREFIX || (cat configure.log && exit 1)
 
 # Verify that gcc_ext isn't linked

```

I went to the folder containing the `recipe` folder (where the `meta.yaml` file is) and typed `conda build .`. This takes some time as it compiles PETSc. Create a new conda environment and add useful stuff

```
conda create -n myEnv
conda activate myEnv
conda install -c conda-forge python=3.7 ipython mpi4py
conda install --use-local petsc
```

I'm not sure these were the exact commands I ran, but something along these lines. Mind the `--use-local`. This will fetch the PETSc compiled by `conda build .` and stored locally. The rest of the packages I fetch from conda-forge. When Conda installs stuff, you will see where the package comes from. Be absolutely sure that it uses your local petsc.

Next, it was necessary for me to also re-compile petsc4py. Perhaps it checks whether PETSc is compiled with complex scalars? I don't know. In any case, I cloned petsc4py-feedstock, went to the recipe folder and ran `conda build .` (while inside myEnv). Then I ran `conda install --use-local petsc4py`. Make sure that you get the local petsc4py _and also_ that it doesn't replace the already installed petsc with one on conda-forge or something like that.

Hope that helps.

**Comment by pancetta** [comment] 2020-04-04 07:06
@sigvaldm Awesome, that indeed worked so far. Many thanks for your help!

**Comment by sigvaldm** [comment] 2020-04-04 15:04
@pancetta: You're welcome :)

**Comment by maxime-z** [comment] 2020-08-12 13:48
@sigvaldm thanks for the solution. Just tried to follow it but got plenty of conflicts for dependent packages. Are you using conda-forge channel when doing `conda build`?

**Comment by sigvaldm** [comment] 2020-08-12 16:12
@maxime-z: When I build PETSc I use the locally modified version of PETSc, hence `build conda ..`. Everything else is taken directly from conda-forge, witness the `-c conda-forge` above. Try a clean and minimal environment with everything installed from conda-forge like I explained above. In my experience mixing packages from conda forge with dependants from defaults leads to many conflicts. Perhaps that's the case for you too?

**Comment by maxime-z** [comment] 2020-08-14 08:04
> @maxime-z: When I build PETSc I use the locally modified version of PETSc, hence `build conda ..`. Everything else is taken directly from conda-forge, witness the `-c conda-forge` above. Try a clean and minimal environment with everything installed from conda-forge like I explained above. In my experience mixing packages from conda forge with dependants from defaults leads to many conflicts. Perhaps that's the case for you too?

Yeah, i think that's the cause of the conflicts. I end up by installing petsc from the source...

**Comment by ltalirz** [comment] 2021-06-02 11:42
fixed in https://github.com/conda-forge/petsc-feedstock/pull/110

Once the package is uploaded, you should now be able to `conda install -c conda-forge petsc=*=*complex*`, see https://anaconda.org/conda-forge/petsc/files .
The scalar=real variant remains the default.

**Comment by MarDiehl** [comment] 2021-08-25 04:18
this seems to be implemented
@dalcinl: I suggest to close this issue

**Closed** 2021-08-25 06:09 UTC
