### ISSUE TITLE
How to know which build is for serial/parallel HDF5 and MPICH/OpenMPI?

### ISSUE THREAD

**Issue by piyueh** [conda-forge/petsc-feedstock#139] opened 2022-05-17 23:05 UTC
### Comment:

Sorry if this question is naive. The build string does not have any information regarding which HDF5 (serial or parallel) and MPI implementation are used. Is it possible to make the build string have this information?

**Comment by dalcinl** [comment] 2022-05-18 05:43
Although I can barely keep up with all the changes in the conda ecosystem, I believe adding endless metadata to the build string is not how things should be done. Can you comment on what's your specific use case?

**Comment by dalcinl** [comment] 2022-05-18 15:40
> ... The installed PETSc did not have parallel HDF5 support even though the runtime HDF5 library has that.

That sounds like a conda bug resolving dependencies.

**Comment by piyueh** [comment] 2022-05-18 17:55
Not sure if it's a bug in conda or it's an expected behavior. If we look at the dependencies of the following two variants of petsc-3.17.1 (from two of the results of the command `conda search -c conda-forge --info "petsc=3.17.1=real_*"`)

```
------------------------------
file name   : petsc-3.17.1-real_h11d90dd_100.tar.bz2
<too long; deleted>
dependencies:
  - hdf5 >=1.10.6,<1.10.7.0a0 mpi_openmpi_*
  - mumps-mpi >=5.2.1,<5.2.2.0a0
  <other dependencies>

------------------------------
file name   : petsc-3.17.1-real_ha0799d6_100.tar.bz2
<too long; deleted>
dependencies:
  - hdf5 >=1.12.1,<1.12.2.0a0
  - openmpi >=4.1.3,<5.0a0
  <other dependencies>

```

The build `real_ha0799d6_100` only needs `hdf5` package to match `>=1.12.1,<1.12.2.0a0`, meaning `hdf5=1.12.1=mpi_openmpi_h41b9b70_4` is perfectly fine with `real_ha0799d6_100` build. So it seems nothing wrong with conda installing the parallel HDF5 and PETSc `real_ha0799d6_100` when doing `conda install -c conda-forge "hdf5=*=mpi_openmpi*" "petsc=3.17.1"`.

However, `petsc=3.17.1=real_ha0799d6_100` was not compiled against OpenMPI-enabled HDF5 because it used a regular `hdf5` package at build time. So `petsc=3.17.1=real_ha0799d6_100` does not work with `hdf5=1.12.1=mpi_openmpi_h41b9b70_4` at runtime. (If PETSc is not compiled against parallel HDF5 at build time, some code is disabled.)

**Comment by dalcinl** [comment] 2022-05-18 18:18
@minrk I need your help here.

**Comment by minrk** [comment] 2022-05-19 08:58
It has to do with the fact that building against serial hdf5 _is_ compatible with running against mpi hdf5 (but not the other way around). So it's a valid solution with the information given, and we haven't specified anything to _prefer_ the parallel hdf5 builds.

I have a question, though: why are there serial hdf5 builds of petsc? petsc requires mpi, so what is the benefit of having builds with serial hdf5? I don't see a reason given in #86, and I don't know enough about petsc or hdf5 to say whether or when there would be a benefit.

I see two solutions:

1. (simplest) remove the serial hdf5 builds. Unless you know a good reason to keep them.
2. make sure petsc + hdf5 serial builds have a runtime dependency on `hdf5 * nompi` to explicitly reject running with serial hdf5. This would make the above install work as intended.

The build matrix in #86 doesn't actually ensure serial hdf5 builds, since it only requests _any_ hdf5, which _may_ be the nompi variant.

**Comment by minrk** [comment] 2022-05-19 09:51
#142 removes the serial hdf5 builds. I can do another PR fixing the serial hdf5 builds if you know a reason to keep them.

**Comment by minrk** [comment] 2022-05-19 18:23
#143 does the alternative - pin serial-hdf5 builds to serial-hdf5 at runtime. Both are valid! I'll let @dalcinl pick which makes the most sense for petsc

**Closed** 2022-05-20 07:31 UTC
Labels: question
